version: "3.4"

services:
    # gamezone.sqlserver:
        # image: gamezoneacr.azurecr.io/gamezone-sql-server:development-v1
        # container_name: gamezone-sql-server
        # build: 
            # context: ../sql
            # dockerfile: ./Dockerfile
        # ports:
            # - "1433:1433"
        # environment:
            # SA_PASSWORD: "Mudar123intrA"
            # ACCEPT_EULA: "Y"     
        # networks:
          # - gamezone            

    gamezone-news-webapp:
        image: gamezoneacr.azurecr.io/gamezone-news-webapp:development-v2
        #container_name: gamezone-news-webapp
        build:
            context: ../Source
            dockerfile: ./WebApps/GameZone.News.WebApp/Dockerfile
        restart: always 
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:7043
            - ASPNETCORE_Kestrel__Certificates__Default__Password=123@Fiap
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/gamezone-certificate.pfx
        volumes:
            - certs:/https:ro
        networks:
          - gamezone
        depends_on:
            - gamezone-identidade-api
            - gamezone-blog-api

    gamezone-identidade-api:
        image: gamezoneacr.azurecr.io/gamezone-api-identidade:development-v2
        container_name: gamezone-api-identidade    
        build: 
            context: ../Source
            dockerfile: ./Identidade/0-Presentation/API/gamezone.Identidade.API/Dockerfile  
        restart: always    
        ports:
            - "5501:5501"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:5501;http://+5502
            - ASPNETCORE_Kestrel__Certificates__Default__Password=123@Fiap
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/gamezone-certificate.pfx
        volumes:
            - certs:/https:ro
        networks:
          - gamezone
        #depends_on:
            #- gamezone.sqlserver
            
    gamezone-blog-api:
        image: gamezoneacr.azurecr.io/gamezone-api-blog:development-v2
        container_name: gamezone-api-blog    
        build: 
            context: ../Source
            dockerfile: ./Blog/0-Presentation/API/gamezone.Blog.API/Dockerfile
        restart: always    
        ports:
            - "5401:5401"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:5401;http://+5402
            - ASPNETCORE_Kestrel__Certificates__Default__Password=123@Fiap
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/gamezone-certificate.pfx
        volumes:
            - certs:/https:ro
        networks:
          - gamezone
        depends_on:
            - gamezone-identidade-api
            #- gamezone.sqlserver  


    gamezone-gamezoneserver:
        image: gamezoneacr.azurecr.io/gamezone-server:development-v2
        container_name: gamezone-server    
        build: 
            context: ./
            dockerfile: ./nginx/Dockerfile 
        restart: always 
        ports:
            - "80:80"
            - "443:443"
        networks:
          - gamezone
        depends_on:
            - gamezone-news-webapp

networks:
  gamezone:
    driver: bridge
    

volumes:
  certs:
    driver: azure_file
    driver_opts:
      share_name: https
      storage_account_name: gamezonetech