version: "3.8"

services:

    sql-server:
        image: techchallengefiapgroup31/gamezone-sql-server:development-v1
        container_name: gamezone-sql-server
        build: 
            context: ../sql
            dockerfile: ./Dockerfile
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Mudar123intrA"
            ACCEPT_EULA: "Y"     
        networks:
          - gamezone            

    web-app:
        image: techchallengefiapgroup31/gamezone-news-webapp:development-v1
        #container_name: gamezone-news-webapp
        build:
            context: ../Source
            dockerfile: ./WebApps/GameZone.News.WebApp/Dockerfile
        restart: always 
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:7043
        networks:
          - gamezone
        depends_on:
            - api-identidade
            - api-blog

    api-identidade:
        image: techchallengefiapgroup31/gamezone-api-identidade:development-v1
        container_name: gamezone-api-identidade    
        build: 
            context: ../Source
            dockerfile: ./Identidade/0-Presentation/API/gamezone.Identidade.API/Dockerfile  
        restart: always    
        ports:
            - "5501:5501"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:5501;http://+5502
            - ASPNETCORE_Kestrel__Certificates__Default__Password=123@Fiap
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/gamezone-certificate.pfx
        volumes:
            - ./certs:/https:ro
        networks:
          - gamezone
        depends_on:
            - sql-server
            
    api-blog:
        image: techchallengefiapgroup31/gamezone-api-blog:development-v1
        container_name: gamezone-api-blog    
        build: 
            context: ../Source
            dockerfile: ./Blog/0-Presentation/API/gamezone.Blog.API/Dockerfile
        restart: always    
        ports:
            - "5401:5401"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:5401;http://+5402
            - ASPNETCORE_Kestrel__Certificates__Default__Password=123@Fiap
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/gamezone-certificate.pfx
        volumes:
            - ./certs:/https:ro
        networks:
          - gamezone
        depends_on:
            - api-identidade
            - sql-server  


    gamezone-server:
        image: techchallengefiapgroup31/gamezone-server:development-v1
        container_name: gamezone-server    
        build: 
            context: ./
            dockerfile: ./nginx/Dockerfile 
        restart: always 
        ports:
            - "80:80"
            - "443:443"
        networks:
          - gamezone
        depends_on:
            - web-app

networks:
  gamezone:
    driver: bridge
    
