# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container - gamezone

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_push_acr:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v3.6.0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Use the desired .NET 6 version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.10.0

    - name: Log in to registry
      uses: docker/login-action@v2.2.0
      with:
        registry: https://gamezoneacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername }}
        password: ${{ secrets.AzureAppService_ContainerPassword }}

    - name: Build and push gamezone-news-webapp container image to registry
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: gamezoneacr.azurecr.io/gamezone-news-webapp:development-v${{ github.run_number }}
        file: ./Source/WebApps/GameZone.News.WebApp/Dockerfile

    - name: Build and push gamezone-api-identidade container image to registry
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: gamezoneacr.azurecr.io/gamezone-api-identidade:development-v${{ github.run_number }}
        file: ./Source/Identidade/0-Presentation/API/GameZone.Identidade.API/Dockerfile

    - name: Build and push gamezone-api-blog container image to registry
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: gamezoneacr.azurecr.io/gamezone-api-blog:development-v${{ github.run_number }}
        file: ./Source/Blog/0-Presentation/API/GameZone.Blog.API/Dockerfile

  deploy_to_aci_gamezone_news_webapp:
    needs: build_and_push_acr  # Aguarda a conclusão do job de build
    runs-on: 'ubuntu-latest'

    steps:
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Instances gamezone-identidade-api to ACI
      uses: Azure/aci-deploy@v1
      with:
        resource-group: rg-GameZone
        name: gamezone-identidade-api
        dns-name-label: gamezone-identidade-api
        image: 'gamezoneacr.azurecr.io/gamezone-api-identidade:development-v${{ github.run_number }}'
        cpu: 0.5   #Optional
        memory: 1.5   #Optional
        registry-username: ${{ secrets.AzureAppService_ContainerUsername }}
        registry-password: ${{ secrets.AzureAppService_ContainerPassword }}
        container-name: gamezone-identidade-api
        location: 'west us'
        azure-file-volume-account-name: gamezonetech
        azure-file-volume-account-key: ${{ secrets.AZURE_FILE_VOLUME_KEY }}
        azure-file-volume-share-name: https
        azure-file-volume-mount-path: /https
        environment-variables: ASPNETCORE_ENVIRONMENT=Development ASPNETCORE_URLS=https://+:5501;http://+5502 ASPNETCORE_Kestrel__Certificates__Default__Path=/https/gamezone-identidade-certificate.pfx
        secure-environment-variables: ASPNETCORE_Kestrel__Certificates__Default__Password=${{ secrets.ASPNETCORE_Kestrel__Certificates__Default__Password }} 
        ports: 5501


    - name: Deploy to Azure Container Instances gamezone-blog-api to ACI
      uses: Azure/aci-deploy@v1
      with:
        resource-group: rg-GameZone
        name: gamezone-blog-api
        dns-name-label: gamezone-blog-api
        image: 'gamezoneacr.azurecr.io/gamezone-api-blog:development-v${{ github.run_number }}'
        cpu: 0.5   #Optional
        memory: 1.5   #Optional
        registry-username: ${{ secrets.AzureAppService_ContainerUsername }}
        registry-password: ${{ secrets.AzureAppService_ContainerPassword }}
        container-name: gamezone-blog-api
        location: 'west us'
        azure-file-volume-account-name: gamezonetech
        azure-file-volume-account-key: ${{ secrets.AZURE_FILE_VOLUME_KEY }}
        azure-file-volume-share-name: https
        azure-file-volume-mount-path: /https
        environment-variables: ASPNETCORE_ENVIRONMENT=Development ASPNETCORE_URLS=https://+:5401;http://+5402 ASPNETCORE_Kestrel__Certificates__Default__Path=/https/gamezone-certificate.pfx
        secure-environment-variables: ASPNETCORE_Kestrel__Certificates__Default__Password=${{ secrets.ASPNETCORE_Kestrel__Certificates__Default__Password }} 
        ports: 5401

    - name: Deploy gamezone-webapp to ACI
      uses: azure/aci-deploy@v1
      with:
        resource-group: rg-GameZone
        dns-name-label: gamezone-webapp'
        image: 'gamezoneacr.azurecr.io/gamezone-news-webapp:development-v${{ github.run_number }}'
        registry-login-server: 'gamezoneacr.azurecr.io'
        registry-username: ${{ secrets.AzureAppService_ContainerUsername }}
        registry-password: ${{ secrets.AzureAppService_ContainerPassword }}
        container-name: gamezone-webapp
        name: gamezone-webapp
        cpu: 0.5   #Optional
        memory: 1.5   #Optional
        location: 'west us'
        azure-file-volume-account-name: gamezonetech
        azure-file-volume-account-key: ${{ secrets.AZURE_FILE_VOLUME_KEY }}
        azure-file-volume-share-name: https
        azure-file-volume-mount-path: /https
        environment-variables: ASPNETCORE_ENVIRONMENT=Development ASPNETCORE_URLS=http://*:7043 ASPNETCORE_Kestrel__Certificates__Default__Path=/https/gamezone-certificate.pfx
        secure-environment-variables: ASPNETCORE_Kestrel__Certificates__Default__Password=${{ secrets.ASPNETCORE_Kestrel__Certificates__Default__Password }} 
        ports: 80 443 7043


  #deploy:
  #  runs-on: ubuntu-latest
  #  needs: build
  #  environment:
  #    name: 'Development'
  #    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #  steps:
  #  - name: Deploy to Azure Web App
  #    id: deploy-to-webapp
  #    uses: azure/webapps-deploy@v2
  #    with:
  #      app-name: 'gamezone-web'
  #      slot-name: 'Development'
  #      publish-profile: ${{ secrets.AzureAppService_PublishProfile_8bf0cdf89838402c9624046e0921fff2 }}
  #      images: 'gamezoneacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ddbf8620490d4e9081994265ae7cf49d }}/gamezone-news-webapp:${{ github.sha }}'