# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container - gamezone

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_push_acr:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v3.6.0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Use the desired .NET 6 version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.10.0

    - name: Log in to registry
      uses: docker/login-action@v2.2.0
      with:
        registry: https://gamezoneacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername }}
        password: ${{ secrets.AzureAppService_ContainerPassword }}

    - name: Build and push gamezone-news-webapp container image to registry
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: gamezoneacr.azurecr.io/gamezone-news-webapp:development-v${{ github.run_number }}
        file: ./Source/WebApps/GameZone.News.WebApp/Dockerfile

    - name: Build and push gamezone-api-identidade container image to registry
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: gamezoneacr.azurecr.io/gamezone-api-identidade:development-v${{ github.run_number }}
        file: ./Source/Identidade/0-Presentation/API/GameZone.Identidade.API/Dockerfile

    - name: Build and push gamezone-api-blog container image to registry
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: gamezoneacr.azurecr.io/gamezone-api-blog:development-v${{ github.run_number }}
        file: ./Source/Blog/0-Presentation/API/GameZone.Blog.API/Dockerfile

  deploy_to_aci:
    needs: build_and_push_acr  # Aguarda a conclusão do job de build
    runs-on: 'ubuntu-latest'

    steps:
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Instances gamezone-identidade-api to ACI
      uses: Azure/aci-deploy@v1
      with:
        resource-group: rg-GameZone
        name: gamezone-identidade-api
        dns-name-label: gamezone-identidade-api
        image: 'gamezoneacr.azurecr.io/gamezone-api-identidade:development-v${{ github.run_number }}'
        cpu: 0.5   #Optional
        memory: 1.5   #Optional
        registry-username: ${{ secrets.AzureAppService_ContainerUsername }}
        registry-password: ${{ secrets.AzureAppService_ContainerPassword }}
        container-name: gamezone-identidade-api
        location: 'west us'
        azure-file-volume-account-name: gamezonetech
        azure-file-volume-account-key: ${{ secrets.AZURE_FILE_VOLUME_KEY }}
        azure-file-volume-share-name: https
        azure-file-volume-mount-path: /https
        #ports: 5501
        environment-variables: |
          ASPNETCORE_ENVIRONMENT=Production
          #ASPNETCORE_URLS="https://+:5501;http://+5502"
          ASPNETCORE_Kestrel__Certificates__Default__Password=123@Fiap
          ASPNETCORE_Kestrel__Certificates__Default__Path="/https/gamezone-identidade-certificate.pfx"
          ConnectionStrings__ConnectionLocal=""
          ConnectionStrings__Connection="Server=tcp:GameZoneServer.database.windows.net,1433;Initial Catalog=gamezoneDB;Persist Security Info=False;User ID=fernando;Password=123@Mudar;MultipleActiveResultSets=False;Encrypt=true;TrustServerCertificate=False;Connection Timeout=30;"
          AllowedHosts="*"
          EnableLocalExecution="false"
          CultureInfo="pt-BR"
          SymmetricSecurityKey="9ASHDA98H9ah9ha9H9A89n0faspoikgvnhaiopk"
          idadeMinima="16"
          AppTokenSettings__RefreshTokenExpiration=8
          AppSettings__AutenticacaoJwksUrl="https://gamezone-identidade-api.westus.azurecontainer.io:5501/jwks"
        #secure-environment-variables: ConnectionStrings__Connection=${{ secrets.CONNECTION_STRING_SQL }}

        #environment-variables: ConnectionStrings__Connection=${{ secrets.CONNECTION_STRING_SQL }} ASPNETCORE_ENVIRONMENT=Development ASPNETCORE_URLS="https://+:5501;http://+5502" ASPNETCORE_Kestrel__Certificates__Default__Path=/https/gamezone-identidade-certificate.pfx ASPNETCORE_Kestrel__Certificates__Default__Password=123@Fiap ConnectionStrings__ConnectionLocal="" AllowedHosts="*" EnableLocalExecution=false CultureInfo="pt-BR" SymmetricSecurityKey=9ASHDA98H9ah9ha9H9A89n0faspoikgvnhaiopk idadeMinima=16 AppTokenSettings__RefreshTokenExpiration=8 AppSettings__AutenticacaoJwksUrl="https://gamezone-identidade-api.westus.azurecontainer.io:5501/jwks"
        #secure-environment-variables: ConnectionStrings__Connection=${{ secrets.CONNECTION_STRING_SQL }} 


    - name: Deploy to Azure Container Instances gamezone-blog-api to ACI
      uses: Azure/aci-deploy@v1
      with:
        resource-group: rg-GameZone
        name: gamezone-blog-api
        dns-name-label: gamezone-blog-api
        image: 'gamezoneacr.azurecr.io/gamezone-api-blog:development-v${{ github.run_number }}'
        cpu: 0.5   #Optional
        memory: 1.5   #Optional
        registry-username: ${{ secrets.AzureAppService_ContainerUsername }}
        registry-password: ${{ secrets.AzureAppService_ContainerPassword }}
        container-name: gamezone-blog-api
        location: 'west us'
        azure-file-volume-account-name: gamezonetech
        azure-file-volume-account-key: ${{ secrets.AZURE_FILE_VOLUME_KEY }}
        azure-file-volume-share-name: https
        azure-file-volume-mount-path: /https
        #ports: 5401
        environment-variables: |
          ASPNETCORE_ENVIRONMENT=Production
          #ASPNETCORE_URLS="https://+:5401;http://+5402"
          ASPNETCORE_Kestrel__Certificates__Default__Path="/https/gamezone-certificate.pfx"
          ASPNETCORE_Kestrel__Certificates__Default__Password=123@Fiap
          ConnectionStrings__ConnectionLocal=""
          ConnectionStrings__Connection="Server=tcp:GameZoneServer.database.windows.net,1433;Initial Catalog=gamezoneDB;Persist Security Info=False;User ID=fernando;Password=123@Mudar;MultipleActiveResultSets=False;Encrypt=true;TrustServerCertificate=False;Connection Timeout=30;"
          ConfigsAzure__ConnectionStorageAccount="DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=gamezonetech;AccountKey=5TJ3lLCg6m9doXpm2VbXw2QGLJ4ItxsbjPkrMA7wRUPMBR7Gt2ybQwmXVugqAvK46vR+qZxf2yZO+AStUALfHQ=="
          AllowedHosts="*"
          EnableLocalExecution="false"
          CultureInfo="pt-BR"
          SymmetricSecurityKey="9ASHDA98H9ah9ha9H9A89n0faspoikgvnhaiopk"
          AppSettings__AutenticacaoJwksUrl="https://gamezone-identidade-api.westus.azurecontainer.io:5501/jwks"
          ConfigsAzure__ContainerBlobStorage="images"
        #secure-environment-variables: |
        #  ConnectionStrings__Connection=${{ secrets.CONNECTION_STRING_SQL }}
        #  ConfigsAzure__ConnectionStorageAccount=${{ secrets.CONNECTION_STORAGE_ACCOUNT }}

        #environment-variables: ConnectionStrings__Connection=${{ secrets.CONNECTION_STRING_SQL }} ConfigsAzure__ConnectionStorageAccount==${{ secrets.CONNECTION_STORAGE_ACCOUNT }} ASPNETCORE_ENVIRONMENT=Development ASPNETCORE_URLS=https://+:5401;http://+5402" ASPNETCORE_Kestrel__Certificates__Default__Path=/https/gamezone-certificate.pfx ASPNETCORE_Kestrel__Certificates__Default__Password=123@Fiap  ConnectionStrings__ConnectionLocal="" AllowedHosts="*" EnableLocalExecution=false CultureInfo="pt-BR" SymmetricSecurityKey=9ASHDA98H9ah9ha9H9A89n0faspoikgvnhaiopk AppSettings__AutenticacaoJwksUrl="https://gamezone-identidade-api.westus.azurecontainer.io:5501/jwks" ConfigsAzure__ContainerBlobStorage=images
        #secure-environment-variables: ConnectionStrings__Connection=${{ secrets.CONNECTION_STRING_SQL }} ConfigsAzure__ConnectionStorageAccount==${{ secrets.CONNECTION_STORAGE_ACCOUNT }} 


    #- name: Set Web App ACR authentication
    #  uses: Azure/appservice-settings@v1
    #  with:
    #     app-name: gamezone-web 
    #     app-settings-json: |
    #       [
    #           {
    #               "name": "ASPNETCORE_ENVIRONMENT",
    #               "value": "Development",
    #               "slotSetting": false
    #           },
    #           {
    #               "name": "ASPNETCORE_URLS",
    #               "value": "http://*:7043",
    #               "slotSetting": false
    #           },
    #           {
    #               "name": "ASPNETCORE_Kestrel__Certificates__Default__Path",
    #               "value": "/https/gamezone-certificate.pfx",
    #               "slotSetting": false
    #           },
    #           {
    #               "name": "ASPNETCORE_Kestrel__Certificates__Default__Password",
    #               "value": "123@Fiap",
    #               "slotSetting": false
    #           },
    #           {
    #               "name": "EnableLocalExecution",
    #               "value": "false",
    #               "slotSetting": false
    #           },
    #           {
    #               "name": "CultureInfo",
    #               "value": "pt-BR",
    #               "slotSetting": false
    #           },
    #           {
    #               "name": "SymmetricSecurityKey",
    #               "value": "9ASHDA98H9ah9ha9H9A89n0faspoikgvnhaiopk",
    #               "slotSetting": false
    #           },
    #           {
    #               "name": "AppSettings__AutenticacaoJwksUrl",
    #               "value": "https://gamezone-identidade-api.westus.azurecontainer.io:5501/jwks",
    #               "slotSetting": false
    #           },
    #           {
    #               "name": "AutenticacaoUrl",
    #               "value": "https://gamezone-identidade-api.westus.azurecontainer.io:5501",
    #               "slotSetting": false
    #           },
    #           {
    #               "name": "BlogUrl",
    #               "value": "https://gamezone-blog-api.westus.azurecontainer.io:5401",
    #               "slotSetting": false
    #           },
    #           {
    #               "name": "LocalPathImages",
    #               "value": "",
    #               "slotSetting": false
    #           }
    #       ]

    #- name: 'Deploy to Azure Web App for Container'
    #  uses: azure/webapps-deploy@v2
    #  with: 
    #    app-name: gamezone-web 
    #    images: gamezoneacr.azurecr.io/gamezone-news-webapp:development-v${{ github.run_number }}


    #- name: Deploy gamezone-web to ACI
    #  uses: azure/aci-deploy@v1
    #  with:
    #    resource-group: rg-GameZone
    #    dns-name-label: gamezone-web
    #    image: 'gamezoneacr.azurecr.io/gamezone-news-webapp:development-v${{ github.run_number }}'
    #    registry-login-server: 'gamezoneacr.azurecr.io'
    #    registry-username: ${{ secrets.AzureAppService_ContainerUsername }}
    #    registry-password: ${{ secrets.AzureAppService_ContainerPassword }}
    #    container-name: gamezone-web
    #    name: gamezone-web
    #    cpu: 0.5   #Optional
    #    memory: 1.5   #Optional
    #    location: 'west us'
    #    azure-file-volume-account-name: gamezonetech
    #    azure-file-volume-account-key: ${{ secrets.AZURE_FILE_VOLUME_KEY }}
    #    azure-file-volume-share-name: https
    #    azure-file-volume-mount-path: /https
    #    ports: 80 443 
    #    environment-variables: |
    #        ASPNETCORE_ENVIRONMENT=Production 
    #        #ASPNETCORE_URLS="http://*:7043" 
    #        ASPNETCORE_Kestrel__Certificates__Default__Path=/https/gamezone-certificate.pfx 
    #        ASPNETCORE_Kestrel__Certificates__Default__Password=123@Fiap 
    #        AllowedHosts="*" 
    #        EnableLocalExecution=false 
    #        CultureInfo="pt-BR" 
    #        SymmetricSecurityKey=9ASHDA98H9ah9ha9H9A89n0faspoikgvnhaiopk 
    #        AppSettings__AutenticacaoJwksUrl="https://gamezone-identidade-api.westus.azurecontainer.io:5501/jwks" 
    #        AutenticacaoUrl="https://gamezone-identidade-api.westus.azurecontainer.io:5501" 
    #        BlogUrl="https://gamezone-blog-api.westus.azurecontainer.io:5401" 
    #        LocalPathImages=""

        #environment-variables: ASPNETCORE_ENVIRONMENT=Development ASPNETCORE_URLS=http://*:7043 ASPNETCORE_Kestrel__Certificates__Default__Path=/https/gamezone-certificate.pfx ASPNETCORE_Kestrel__Certificates__Default__Password=123@Fiap AllowedHosts="*" EnableLocalExecution=false CultureInfo="pt-BR" SymmetricSecurityKey=9ASHDA98H9ah9ha9H9A89n0faspoikgvnhaiopk AppSettings__AutenticacaoJwksUrl="https://gamezone-identidade-api.westus.azurecontainer.io:5501/jwks" AutenticacaoUrl="https://gamezone-identidade-api.westus.azurecontainer.io:5501" BlogUrl="https://gamezone-blog-api.westus.azurecontainer.io:5401" LocalPathImages=""
        #secure-environment-variables: ASPNETCORE_Kestrel__Certificates__Default__Password=${{ secrets.ASPNETCORE_Kestrel__Certificates__Default__Password }} 