name: Build and deploy container app to Azure Web App - gamezone-webapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x  # Use the desired .NET 6 version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://gamezoneacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1a07b17dde80472bb461c5876d2efc64 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e45e0de6f7cc49b2b7c0d13adfbf9db9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: gamezoneacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1a07b17dde80472bb461c5876d2efc64 }}/gamezone-news-webapp:${{ github.sha }}
        file: ./Source/WebApps/GameZone.News.WebApp/Git.Dockerfile

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'gamezone-webapp'
        slot-name: 'Development'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2045d12b5e4244a594e686210bf1164a }}
        images: 'gamezoneacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1a07b17dde80472bb461c5876d2efc64 }}/gamezone-news-webapp:${{ github.sha }}
